### ISSUE TITLE
Error during parsing. Unable to use this module

### ISSUE THREAD

**Issue by juneflowers** [caddy-dns/googleclouddns#2]
Hi I would really like to implement this functionality into my caddy configuration and have followed the instructions as specified. My service account file is set as an environment variable and my project name is listed correctly. However Caddy throws these errors.

```
{"level":"info","ts":1633719124.0289392,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
run: adapting config using caddyfile: parsing caddyfile tokens for 'acme_dns': /etc/caddy/Caddyfile:3 - Error during parsing: getting module named 'dns.providers.googleclouddns': module not registered: dns.providers.googleclouddns
```

My configuration is as such
```
{
    email egg@domain.org
    acme_dns googleclouddns {
        gcp_project tofu-382304
   }
}


www.web.domain.org {
	redir https://web.domain.org
}

web.domain.org {
   reverse_proxy localhost:8080
   log {
   output file /data/service.log
   format single_field common_log
   }
   encode {
          gzip 6
          br 5
   }
   import security.conf
   handle_errors {
          rewrite * /{http.error.status_code}
          reverse_proxy https://http.cat {
          header_up Host http.cat
   }
   }
}
```
![image](https://user-images.githubusercontent.com/63337938/136612144-92a02d34-aba6-451b-9b0e-e09198276407.png)
![image](https://user-images.githubusercontent.com/63337938/136612156-b2d9d9cb-2358-4e8d-b54b-6b6c0b491345.png)

**Comment by juneflowers** [comment]
Nevermind! I didn't realize I had to add https://github.com/libdns/googleclouddns to the build as well as this module. It works now.

**Comment by mholt** [comment]
Hmm that doesn't sound right. What did you do different?

**Comment by juneflowers** [comment]
I rebuilt my caddy image with 
github.com/caddy-dns/googleclouddns
github.com/libdns/googleclouddns 

I didn't have the libdns module previously. I can confirm it works now as I issued 25 certificates earlier and they all successfully passed dns-01 challenges

**Comment by mholt** [comment]
You should only need to build with github.com/caddy-dns/googleclouddns, since that is a Caddy module, whereas github.com/libdns/googleclouddns is not. What was your xcaddy command for the build that gave you that error, versus the command for the build that worked? (Or the main.go file if not using xcaddy)

**Comment by juneflowers** [comment]
That's weird then yeah haha. Well I use docker so I just built my docker image with this dockerfile. just running a simple "docker build . -t duckyface/caddy" 
```
FROM caddy:2-builder-alpine AS builder

RUN xcaddy build \
    --with github.com/ueffel/caddy-brotli \
    --with github.com/caddy-dns/googleclouddns \
    --with github.com/libdns/googleclouddns 
       
FROM caddy:2-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

**Comment by brockwood** [comment]
This is an interesting issue. I've been trying to reproduce what you are seeing and have been unable to. 

Here's the `Dockerfile` I'm using based on your original minus `libdns/googleclouddns`:

```Dockerfile
FROM caddy:2-builder-alpine AS builder

RUN xcaddy build \
    --with github.com/ueffel/caddy-brotli \
    --with github.com/caddy-dns/googleclouddns

FROM caddy:2-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

The Docker build command:

```bash
docker build -t test-caddy -f ./Dockerfile ./
```

The `Caddyfile` based on your example above (switched to the staging directory):

```Caddyfile
{
	acme_ca https://acme-staging-v02.api.letsencrypt.org/directory
	email user@home.com
	acme_dns googleclouddns {
		gcp_project fake-project
	}
}

server.fake.zone {
	reverse_proxy localhost:8080
	log {
		output file /data/service.log
		format single_field common_log
	}
	encode {
		gzip 6
		br 5
	}
	handle_errors {
		rewrite * /{http.error.status_code}
		reverse_proxy https://http.cat {
			header_up Host http.cat
		}
	}
}

```

Finally, ran the new image with the command:

```
docker run -it --rm -p 80:80 -p 443:443 -v $PWD/Caddyfile:/etc/caddy/Caddyfile -v $PWD/data:/data test-caddy
```

Caddy runs (though it is unable to get a certificate since I didn't provide a real DNS zone or Google Application Credentials). The errors reported are coming from the `googleclouddns` Caddy module, though, so it is compiled in. I'm curious if I'm doing something different than what you did.

**Comment by juneflowers** [comment]
That sure is curious. No as far as I can tell nothing is different. What I find the weirdest is why it successfully builds with something that isn't a caddy module lol. Okay I just commented out the libdns repo and rebuilt it and it built and started up just fine now lol. makes no sense
