### ISSUE TITLE
Is this project not an official Caddy module?

### ISSUE THREAD

**Issue by Hartimer** [caddy-dns/googleclouddns#3]
I was attempting to configure Caddy via Ansible, which leverages the following download link:

https://caddyserver.com/api/download?os=linux&arch=arm64&p=github.com/caddy-dns/googleclouddns

However the above produces

```
{"status_code":400,"error":{"message":"github.com/caddy-dns/googleclouddns is not a registered Caddy module package path","id":"9e1f7f41-ad69-40d3-9535-b32c6962145d"}}
```

This module also doesn't show up on Caddy's download page https://caddyserver.com/download.

**Comment by brockwood** [comment]
Apologies. I had missed setting this up on https://caddyserver.com/. It is registered and should now be available.

**Comment by Hartimer** [comment]
Thank you @brockwood, it is working as expected now.
